"""initial migration

Revision ID: 88657027ec6d
Revises: 
Create Date: 2024-11-22 03:59:29.656748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88657027ec6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('post_title', sa.Text(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('vector_embedding', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_log',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_table('topic',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('topic_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('search_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('search_log')
    op.drop_table('comments')
    # ### end Alembic commands ###
