"""Initial migration

Revision ID: a76593906cf8
Revises: 
Create Date: 2024-11-21 18:11:23.382735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76593906cf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_log')
    op.drop_table('comments')
    op.drop_table('topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.NUMERIC(), nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('post_title', sa.TEXT(), nullable=False),
    sa.Column('comment_text', sa.TEXT(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sentiment', sa.VARCHAR(length=20), nullable=False),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('vector_embedding', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_log',
    sa.Column('search_id', sa.NUMERIC(), nullable=False),
    sa.Column('query_text', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('result_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('search_id')
    )
    # ### end Alembic commands ###
